name: shop
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  iconsax: ^0.0.8
  dio: ^5.7.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  get_storage: ^2.1.1
  flutter_map: ^7.0.2
  share_plus: ^10.0.3
  webview_flutter: ^4.10.0
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # Fonts
  fonts:
    - family: yb
      fonts:
        - asset: assets\fonts\eb.ttf
          weight: 900
        - asset: assets\fonts\b.ttf
          weight: 700
        - asset: assets\fonts\r.ttf
          weight: 500

